[hyprland]
description = "hyprland with lua"
version = "0.56.1"
pre_command = "hyprctl eval 'hl.config({misc={disable_autoreload=true}})' || true" # Make sure the global run hyprctl reload
post_command = "echo 'Please run 'hyprctl reload' Just incase for errors and to apply the new configuration'"

[[hyprland.dependency]]
pacman = ["hyprland"]
dnf = ["hyprland"]

[[hyprland.files]]
action = "sync"
source_root = "Configs/.local/share/hypr/"
target_root = "${XDG_DATA_HOME}/hypr/"
paths = ["lua", "hyde.lua", "schema/hyprland-lua.json"]
ignored_paths = ["*.conf", ".vscode"]

[[hyprland.files]]
action = "preserve"
source_root = "Configs/.config/hypr"
target_root = "${XDG_CONFIG_HOME}/hypr/"
paths = ["hyprland.lua", "monitors.lua"]
